CC = gcc
CFLAGS = -Wall -Wextra -O2 -std=c99
LDFLAGS = -lm

# Default target
all: piano_model piano_compact

# Compile the basic model (with zero weights)
piano_model: piano_model.c
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

# Compile the compact model (with embedded weights)
piano_compact: piano_compact.c
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

# Compile the model with extracted weights (generated by extract_weights.py)
piano_model_weights: piano_model_with_weights.c
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

# Generate the C file with weights from the trained model
extract_weights: extract_weights.py
	python3 extract_weights.py

# Clean build artifacts
clean:
	rm -f piano_model piano_model_weights piano_model_with_weights.c piano_compact

# Run tests
test: piano_model
	./piano_model

test_weights: piano_model_weights
	./piano_model_weights

test_compact: piano_compact
	./piano_compact

.PHONY: all clean test test_weights test_compact extract_weights
